version: '3'
services:
  app:
    container_name: ${APP_SERVICE}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: blog
        uid: 1000
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - "./:/var/www/html/blog"
      - "./docker/php.ini:/usr/local/etc/php/php.ini"
      - ~/.local/share/fish/fish_history:/home/blog/.local/share/fish/fish_history
    networks:
      - blog-network
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    networks:
      - blog-network
networks:
  blog-network:
    driver: bridge